includes:
- configs/datasets/hateful_memes/bert.yaml

model_config:
  mutan_bert:
    classifier:
      type: mlp
      params:
        num_layers: 2
    losses:
    - type: cross_entropy

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 500
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 4.51652551e-03
    eps: 1e-8

evaluation:
  metrics:
  - accuracy
  - binary_f1
  - roc_auc

training:
  batch_size: 64
  lr_scheduler: true
  max_updates: 10000
  early_stop:
    criteria: hateful_memes/roc_auc
    minimize: false

checkpoint:
  pretrained_state_mapping:
    base: base